### ISSUE TITLE
Unexpected identifier

### ISSUE THREAD

**Issue by gregorwolf** [klimapartner/co-collmex#2]
Ich versuche gerade den Zugriff zunächst einmal mit einem einfachen script zum laufen zu bringen und habe die Beispiele aus der README mit meinen Zugangsdaten versehen. Leider tritt mit node 
v11.10.0 und auch v10.15.1 beim aufruf von `node index.js` dieser Fehler auf:

```
var res = yield collmex.get({Satzart:"PRODUCT_GET",Produktnummer:1})
                ^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:85:7)
    at createScript (vm.js:266:10)
    at Object.runInThisContext (vm.js:314:10)
    at Module._compile (internal/modules/cjs/loader.js:698:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:801:12)
    at internal/main/run_main_module.js:21:11
```

**Comment by Holger-Will** [comment]
sorry, irgendwie ist der Bug hier untergegangen... hab ich grad erst gesehen ;-)
yield ist nur innerhalb von Generatorfunktionen nutzbar:

function* bla(){
var res = yield collmex.get({Satzart:"PRODUCT_GET",Produktnummer:1})
}

kannst bitte Du nochmal prüfen ob Du irgendwo das * vergessen hast.

ich werde das  modul demnächst mal aktualisieren und auf async/await umstellen.

Sorry nochmal für die späte Antwort.

**Comment by gregorwolf** [comment]
Kein Problem. Ich habe etwas später festgestellt, dass ich mit der plus Version ja noch gar keinen API Zugriff habe. Meine Anforderung konnte ich jetzt durch den CSV Export und ein kleines NodeJS Script lösen.
